name: Sync awesome-software-engineering-games

on:
  workflow_dispatch:
  repository_dispatch:
    types: [game-list-update]

jobs:
  sync-awesome-software-engineering-games:
    name: Sync awesome-software-engineering-games from external repository
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: website-admin

    steps:
      - uses: actions/checkout@v6.0.1
      - uses: actions/setup-go@v6
        with:
          go-version: "1.25"

      - name: Build
        run: make build

      # Updates the Awesome Software Engineering Games data
      # from https://github.com/EngineeringKiosk/awesome-software-engineering-games
      - name: website-admin sync awesome-software-engineering-games
        run: |
          ./website-admin sync awesome-software-engineering-games

      # Commit results back to repository
      - uses: stefanzweifel/git-auto-commit-action@v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: "chore: Update the latest data from awesome-software-engineering-games"
          branch: main
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions Bot <actions@github.com>"